Fix bug in #get_all when the user lacks permission
Try `NetSuite::Records::Currency.get_all` with a role that lacks
Currency List permissions. The response you get is:

  <platformCore:status isSuccess="false">
    <platformCore:statusDetail type="ERROR">
      <platformCore:code>INSUFFICIENT_PERMISSION</platformCore:code>
      <platformCore:message>Permission Violation: You need  the
        'Lists -&gt; Currency' permission to access this page. Please
        contact your account administrator.</platformCore:message>
    </platformCore:statusDetail>
  </platformCore:status>

Because of this `response_hash[:record_list]` is `nil`, and so
`response_hash[:record_list][:record]` raises:

  NoMethodError: undefined method `[]' for nil:NilClass

This prevents that from happening